on:
  workflow_call:
    secrets:
      automation_github_token:
        required: true

jobs:
  automation-changelog-update:
    name: "Changelog - Update"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Restore Automation cache"
        uses: "actions/cache@v2"
        with:
          path: |
            cache
          key: "${{ runner.os }}-automation-${{ hashFiles('**/CHANGELOG.md') }}"
          restore-keys: |
            ${{ runner.os }}-automation-

      - name: "Update Changelog File"
        uses: "docker://aeonphp/automation:latest"
        env:
          AEON_AUTOMATION_GH_TOKEN: "${{ secrets.automation_github_token }}"
          EON_AUTOMATION_CACHE_DIR: "/github/workspace/cache"
        with:
          entrypoint: "/composer/vendor/bin/automation"
          args: "changelog:generate ${{ github.repository }} --github-file-update-path=CHANGELOG.md --skip-from=\"dependabot[bot]\" --skip-from=\"aeon-automation\""
