on:
  workflow_call:
    secrets:
      automation_github_token:
        required: true

jobs:
  automation-changelog-new-release:
    name: "Changelog - New Release"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Get tag name"
        id: "tag-name"
        run: |
          tag=$(echo ${{ github.event.ref }} | cut -c11-)
          echo "::set-output name=tag::$tag"

      - name: "Add new release to Changelog File"
        uses: "docker://aeonphp/automation:latest"
        env:
          AEON_AUTOMATION_GH_TOKEN: "${{ secrets.automation.github_token }}"
        with:
          entrypoint: "/composer/vendor/bin/automation"
          args: "changelog:release:unreleased ${{ github.repository }} CHANGELOG.md ${{ steps.tag-name.outputs.tag }} --github-file-changelog-update"
